name: Run Format Script

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create format.sh file
        run: |
          cat << 'EOF' > format.sh
          #!/bin/bash
          #find . -wholename "rime-out/tests"
          
          input(){
          find . -wholename "./rime-out/tests" | while read inpath; do
              judgedata_path="./judgedata/"
              inputfiles=`ls $inpath | grep ".in$"`
              cnt=1
              for i in $inputfiles
              do
          	#echo "cp" $inpath"/"$i $judgedata_path"/in"$cnt".txt"
                  echo $cnt $i
                  echo $cnt $i | cat >> $judgedata_path"/"case_mapping.txt  
          	cp $inpath"/"$i $judgedata_path"/in"$cnt".txt"
          	cnt=$(($cnt + 1))
              done
              cnt=$(($cnt - 1))
              echo $cnt | cat > $judgedata_path"/"case.txt  
              #echo $cnt
          done
          }
          
          output(){
              find . -wholename "./rime-out/tests" | while read outpath; do
          	judgedata_path="./judgedata/"
          	outputfiles=`ls $outpath | grep ".diff$"`
          	cnt=1 
          	for i in $outputfiles
          	do
          	#echo $outpath"/"$i $judgedata_path"/out"$cnt".txt"
          	    cp $outpath"/"$i $judgedata_path"/out"$cnt".txt"
          	    cnt=$(($cnt+1))
          	done
          	#echo $cnt
              done
          }
          
          mkdir  judgedata
          input
          output
          
          EOF
          chmod +x format.sh
      
      - name: Generate proccess.sh
        run: |
          cat << 'EOF' > process.sh
            #!/bin/bash

            # 生成物を保存するディレクトリ
            mkdir -p generated

            # ルートディレクトリの各サブディレクトリを処理
            for dir in ./*/; do
              # tests ディレクトリが存在するか確認
              if [ -d "${dir}tests" ]; then
                echo "Processing: ${dir}"

                # 対象ディレクトリに移動してフォーマット実行
                (
                  cd "$dir" || exit 1
                  ../format.sh tests
                )

                # judgedata が生成されていればリネームして移動
                judgedata_dir="${dir}judgedata"
                
                if [ -d "$judgedata_dir" ]; then
                  # judgedata を元のディレクトリ名でリネーム
                  base_dir=$(basename "$dir")
                  mv "$judgedata_dir" "./generated/${base_dir}"
                  echo "Moved and renamed judgedata to generated/${base_dir}"
                else
                  echo "No judgedata directory found in ${dir}"
                fi
              fi
            done
          EOF
          chmod +x process.sh

      - name: Ensure process.sh is executable
        run: chmod +x process.sh
        
      - name: Run proccess.sh
        run: ./process.sh

      - name: Clean up
        run: rm format.sh process.sh

      - name: Archive judgedata
        uses: actions/upload-artifact@v4
        with:
          name: judgedata
          path: generated
